schoolproject/schoolapp/urls.py
from .import views
from django.urls import path

urlpatterns = [

    path('',views.home,name='home'),
    path('login', views.login, name='login'),
    path('register', views.register, name='register'),
    path('courses', views.courses, name='courses'),
    path('courses/application', views.application, name='application'),
    path('logout', views.logout, name='logout'),


]

schoolproject/schoolproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('',include('schoolapp.urls')),
]
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

schoolproject/schoolapp/models.py
from django.db import models

# Create your models here.

schoolproject/schoolapp/forms.py
from django import forms

class MyForm(forms.Form):
    department = forms.ChoiceField(choices=[('sc','Select department'),('cs', 'Computer Science'), ('ece', 'Electronics'), ('commerce', 'Commerce'), ('humanities', 'Humanities'), ('math', 'Mathematics')])
    course = forms.ChoiceField(choices=[])

schoolproject/schoolapp/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from django.contrib import messages, auth
from django.shortcuts import render
from .forms import MyForm

# Create your views here.
def home(request):
    return render(request,"home.html")

def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username=username, password=password)

        if user is not None:
            auth.login(request, user)
            return redirect('/courses')
        else:
            messages.info(request, "Invalid Credentials")
            return redirect('login')
    return render(request, "login.html")

def logout(request):
    auth.logout(request)
    return redirect('/')

def register(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        cpass = request.POST['password1']

        if password == cpass:
            if User.objects.filter(username=username).exists():
                messages.info(request, "Username Taken")
                return redirect('register')

            else:
                user = User.objects.create_user(username=username, password=password)

                user.save();
                print("User created")
        else:
            messages.info(request, "Password not matching")
            return redirect('register')
        return redirect('login')
    return render(request, "register.html")

def courses(request):
    return render(request,"courses.html")
def application(request):
    # Initialize the form with department choices
    form = MyForm()
    context = {'form': form}
    if request.method == 'POST':

        messages.success(request, 'Order Confirmed')
        return redirect('application')
    return render(request,"application.html",context)

schoolproject/templates/application.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register for Course</title>

<style>
        .reg_form{
            margin:0 250px;
            padding:30px;
            background-color:Lightblue;
            height:455px;
            }
         .form-column {
            float: left;
            width: 50%;
            box-sizing: border-box;
            padding: 10px;
        }
        textarea{
             border: 1px solid #ccc;
             }

        .form_reg input[type='text'],input[type='email'],input[type='password'],input[type='date']{
            padding:7px;
            width:350px;
            color:#333;
            margin-bottom:15px;
            border: 1px solid #ccc;
            font-size:16px;
            box-sizing:border-box;
            }

            .form_reg input[type='radio']{
            padding:5px;
            position:relative;

            }
        .form_reg label{
            text-align:left;
            font-weight:bold;
            padding:10px 5px;
            margin-bottom:0px;
            }
        .form_reg button{
            padding:10px;
            text-align:center;
            width:750px;
            margin:0px 2px;
            background-color:LightGray;
            font-weight:bold;
            }
      .button{
        background-color:LightGray;
         border: none;
        color: white;
        margin-top:5px;
        padding: 5px 8px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
}
        select {
         width: 350px;
        padding: 6px;
        border: 1px solid #ccc;
        border-radius: 4px;
        background-color: #f8f8f8;
        font-size: 16px;
        color: #333;

}

    </style>
</head>
<body style="background-image:url({% static 'images/about.jpg' %})">
<h3 style="text-align:center;font-family:sans-serif;color:Black">Student Application</h3>

    <div class="reg_form">

        <form action="application" class="form_reg" method="post">
            {% csrf_token %}
            <div class="form-column">
                <label>Username</label><br>
                <input type="text" name="username" placeholder="Enter your username"><br>
                <label>Date of Birth</label><br>
                <input type="date" name="dob" placeholder=""><br>
                <label>Phone Number</label><br>
                <input type="text" name="phone" placeholder="Enter your phone number"><br>
                <label>Address</label><br>
                <textarea rows="6" cols="45"></textarea><br><br>
                <label>Gender</label><br><br>
                <input type="radio" name="gender" >Male
                <input type="radio" name="gender" value="female">Female<br><br>


            </div>
            <div class="form-column">
                <label>Age</label><br>
                <input type="text" name="dob" placeholder="Enter your Age"><br>
                 <label>Email</label><br>
                <input type="email" name="email" placeholder="Enter your email id"><br>

                 <label >Purpose</label>
                <select id="purpose" name="purpose">
                    <option value="na">Select</option>
                    <option value="Enquiry">Enquiry</option>
                    <option value="New Application">New Application</option>
                    <option value="Application status">Application Status</option>
                    <option value="Cancellation">Cancellation</option>

                </select><br>

                {{ form.as_p }}
                <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

                <script>
                $(document).ready(function () {
                // Initialize the "Course" drop-down as empty
                $("#id_course").html("<option value=''>---------</option>");

                // Define a dictionary of department-to-course mappings
                var departmentCourses = {
                'cs': ['BSc Computer Science', 'BCA', 'BTech CS'],
                'ece': ['BTech ECE','BSc Electronics','Diploma'],
                'commerce': ['BCom', 'BBA', 'CA'],
                'humanities': ['BA History', 'BA Literature', 'Philosophy'],
                'math': ['Calculus', 'Linear Algebra', 'Statistics']
                };

                 // Handle change in the "Department" drop-down
                $("#id_department").change(function () {
                    var selectedDepartment = $(this).val();
                    var courseOptions = "<option value=''>---------</option>";

                // Populate the "Course" drop-down based on the selected department
                if (selectedDepartment in departmentCourses) {
                    var courses = departmentCourses[selectedDepartment];
                    for (var i = 0; i < courses.length; i++) {
                        courseOptions += "<option value='" + courses[i] + "'>" + courses[i] + "</option>";
                    }
                }

                $("#id_course").html(courseOptions);
                 });
                });
                </script>

                <label>Material</label><br><br>
                 <input type="checkbox" id="material1" name="material1" value="Pen">
                <label for="material1"> Pen</label>
                <input type="checkbox" id="material2" name="material2" value="Pen">
                <label for="material2"> Notebook</label>
                <input type="checkbox" id="material3" name="material3" value="Calculator">
                <label for="material3">Calculator</label>
                <input type="checkbox" id="material4" name="material4" value="paper">
                <label for="material4">Papers</label><br>

            </div>
             <button type="submit">SUBMIT</button>
        </form>
    </div>
    {% for msg in messages %}
    <h4 style="text-align:center;color:Black;">{{msg}}</h4>
    {% endfor %}
    <div class="button_cont" style="margin-left:600px;">
        <button class="button"><a href="logout" >Logout</a></button>
        <button class="button"><a href="/">Home</a></button>
    </div>
</body>
</html>

schoolproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{%static 'css/custom.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/95607d3679.js" crossorigin="anonymous"></script>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <meta name="description" content="{% block metadescription %}{% endblock %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div class="container">
    {% include 'header.html' %}
    {% include 'navbar.html' %}
    {% block content %}
    {% endblock %}
    {% include 'footer.html' %}
</div>

<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

schoolproject/templates/courses.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
  School store - Join courses
{% endblock %}

{% block title %}
 School store
{% endblock %}

{% block content %}
 <div>
     <center>
      <img class="my_image my_image_padding" src="{%static 'img/course.png' %}" alt=" " width="1100px;" height="400px;">
         <a class="join-link" href="courses/application">Student Application</a>
     </center>
  </div>

{% endblock %}

schoolproject/templates/footer.html
<div class="footer">
  <p class="text-center">
    &copy; ABC tech pvt ltd.All Rights Reserved.
  </p>
</div>

schoolproject/templates/header.html
{% load static %}
<header>
  <center>
     <img src="{% static 'img/SCHOOL STORE.png' %}" alt="logimage" width="150px;" height="150px;">
  </center>
</header>

schoolproject/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
  School store - Buy online school supplies..
{% endblock %}

{% block title %}
 School store
{% endblock %}

{% block content %}
 <div>
     <center>
      <img class="my_image my_image_padding" src="{%static 'img/banner.png' %}" alt=" " width="1100px;" height="450px;">
         {% if user.is_authenticated %}
         <a class="join-link" href="courses">Courses</a>
         {% endif %}
     </center>
  </div>
{% endblock %}

schoolproject/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
    <style>
        .login_form{

            margin:30px 500px;
            padding:30px;
            box-sizing:border-box;
            background-color:lightblue;
            }

        .form_login input{
            padding:10px;
            width:300px;

            border:1px solid blue;
            box-sizing:border-box;

            }
        .form_login label{
            text-align:left;
            font-weight:bold;
            padding:20px 5px;
            }
        .form_login button{
            padding:10px;
            text-align:center;
            width:300px;
            margin:20px 2px;
            background-color:LightGray;
            font-weight:bold;
            }



    </style>
</head>
<body style="background-image:url({% static 'images/about.jpg' %})">
<h2 style="text-align:center;font-family:sans-serif;color:Black">LOG IN</h2>

    <div class="login_form">

        <form action="login" class="form_login" method="post">
            {% csrf_token %}
            <label>Username</label><br>
            <input type="text" name="username" placeholder="Enter your username"><br>
            <label>Password</label><br>
            <input type="password" name="password" placeholder="Enter your password"><br>

            <button type="submit">Log in</button><br>
            <p><center>Not registered ? <a href="register">Register Here</a></center></p>
        </form>
    </div>
  {% for msg in messages %}
    <h2 style="text-align:center;color:Black;">{{msg}}</h2>
    {% endfor %}

</body>
</html>

schoolproject/templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
         <li class="nav-item">
          <a class="nav-link" href="#" style="color:blue;font-size:20px;"><b>SCHOOL STORE</b></a>
        </li>
      </ul>
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="/" style="color:blue;font-size:15px;"><b>Home</b></a>

        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="#" style="color:Black;font-size:15px;">Hi {{user.username}}</a>
        </li>
         <li class="nav-item">
          <a class="nav-link" href="logout" style="color:blue;font-size:15px;">Logout</a>
        </li>
        {% else %}
         <li class="nav-item">
          <a class="nav-link" href="login" style="color:blue;font-size:15px;"><b>Login</b></a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="register" style="color:blue;font-size:15px;"><b>Register</b></a>
          </li>
        {% endif %}
          <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false" style="color:blue;font-size:15px;">
            <b>Department</b>
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Computer_science">Computer Science</a></li>
            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Electronics">Electronics</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Commerce">Commerce</a></li>
              <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Humanities">Humanities</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Mathematics">Mathematics</a></li>

          </ul>
          </li>
      </ul>
      </div>
    </div>
</nav>

schoolproject/templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Registration</title>
    <style>
        .reg_form{

            margin:30px 500px;
            padding:30px;
            box-sizing:border-box;
            background-color:Lightblue;
            }

        .form_reg input{
            padding:10px;
            width:300px;

            border:1px solid blue;
            box-sizing:border-box;

            }
        .form_reg label{
            text-align:left;
            font-weight:bold;
            padding:20px 5px;
            }
        .form_reg button{
            padding:10px;
            text-align:center;
            width:300px;
            margin:20px 2px;
            background-color:LightGray;
            font-weight:bold;
            }


    </style>
</head>
<body style="background-image:url({% static 'images/about.jpg' %})">
<h2 style="text-align:center;font-family:sans-serif;color:Black">Registration</h2>

    <div class="reg_form">

        <form action="register" class="form_reg" method="post">
            {% csrf_token %}
            <label>Username</label><br>
            <input type="text" name="username" placeholder="Enter your username"><br>
            <label>Password</label><br>
            <input type="password" name="password" placeholder="Enter your password"><br>
            <label>Confirm Password</label><br>
            <input type="password" name="password1" placeholder="Confirm your password"><br>
            <button type="submit">REGISTER</button>
        </form>
    </div>
 {% for msg in messages %}
    <h2 style="text-align:center;color:Black;">{{msg}}</h2>
    {% endfor %}

</body>
</html>